会場リストつくりました。
NITACwpl/sports-fes-2023 pull request #37
Opened 2023-11-18 19:04 UTC by yumaa0

## レビュー優先度

- [ ] 🚀 今すぐ確認してほしい
- [ ] 🚗 今日中に確認してほしい
- [ ] 🏃 3日以内に確認してほしい
- [ ] 🐢 5日以内までに確認してほしい

## レビュー深さ

- [ ] 🕵️ 該当Issueから考慮してレビューしてほしい
- [ ] 🧪 ローカルで動作確認してほしい
- [ ] 🔍 コードロジックを理解して確認してほしい
- [ ] 👀 ぱっと確認するだけで良い

## 関連Issue

- ここに書く

## 概要（ざっくり）

- ここに書く

## ユーザー側の変更内容

- ここに書く

## コードの変更内容

- ここに書く

## スクリーンショット（可能であれば）

ここに書く

## レビューに必要な情報

- ここに書く

2023-11-19 05:16 UTC, hengin-eer requested changes
下の吹き出しが崩れちゃってます！
そこだけ修正お願いします

2023-11-19 05:48 UTC, hengin-eer commented
いっそ文字をsvgに含めていいと思う

2023-11-19 06:31 UTC, yumaa0 commented
文字入れました！
これどうすればいいですか？🥲


2023年11月19日(日) 14:49 Hengineer ***@***.***>:

> いっそ文字をsvgに含めていいと思う
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/NITACwpl/sports-fes-2023/pull/37#issuecomment-1817755977>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BD24QBNS7OYRADOYAZVEZWTYFGMUZAVCNFSM6AAAAAA7RFBIF6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQMJXG42TKOJXG4>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-11-20 07:22 UTC, hengin-eer approved these changes
確認してみた

2023-11-20 07:22 UTC, merged